import { useState, useRef, useEffect, useLayoutEffect } from "react";
import { createPortal } from "react-dom";
import { Search, BarChart2, LayoutGrid, TrendingUp, Zap, Settings, Globe, Package, Target, DollarSign, Calendar, Tag, Image, Activity, Map } from "lucide-react";
import bgImage from "@/imports/Frame1213232919/98c6b4368718c38b34a141301b024a2277cf0845.png";

// ─── Types ────────────────────────────────────────────────────────────────────

type RoleId = "executive" | "retail-media" | "ecommerce" | "agency" | "analyst" | "operations";
type PageId = string;

interface MenuItem {
  id: PageId;
  label: string;
  tooltip: string;
}

interface MenuCategory {
  name: string;
  description: string;
  color: string;
  items: MenuItem[];
}

interface RoleDef {
  id: RoleId;
  label: string;
  categories: MenuCategory[];
}

// ─── Data ─────────────────────────────────────────────────────────────────────

const ALL_PAGES: Record<PageId, { title: string; description: string; icon: React.ReactNode }> = {
  "executive-dashboard": { title: "Executive Dashboard", description: "Cross-retailer view of advertising performance, sales, ROAS, user adoption, and automation impact.", icon: <BarChart2 className="size-5" /> },
  "custom-dashboard": { title: "Custom Dashboard", description: "Build and configure personalized dashboards tailored to your workflows and KPIs.", icon: <LayoutGrid className="size-5" /> },
  "custom-metric": { title: "Custom Metric", description: "Define and track bespoke performance metrics aligned to your business goals.", icon: <Target className="size-5" /> },
  "account-activity": { title: "Account Activity Analysis", description: "Detailed view of account-level trends, activity patterns, and performance shifts.", icon: <Activity className="size-5" /> },
  "cross-retailer-sov": { title: "Cross Retailer SOV", description: "Compare share of voice across all retail platforms in a single view.", icon: <Globe className="size-5" /> },
  "automation-value": { title: "Automation Value Insights", description: "Quantify the ROI and efficiency gains generated by Pacvue automation.", icon: <Zap className="size-5" /> },
  "incrementality": { title: "Incrementality", description: "Measure the true incremental impact of your advertising on sales lift.", icon: <TrendingUp className="size-5" /> },
  "budget-plan": { title: "Budget Plan", description: "Allocate and manage budgets across campaigns, retailers, and time periods.", icon: <DollarSign className="size-5" /> },
  "keyword-opportunity": { title: "Keyword Opportunity", description: "Discover high-impact keywords to grow reach and improve ROAS.", icon: <Search className="size-5" /> },
  "share-tag": { title: "Share Tag", description: "Tag and share campaign segments for cross-team collaboration.", icon: <Tag className="size-5" /> },
  "creative-hub": { title: "Creative Hub", description: "Centralized management for organizing and deploying creative assets across campaigns.", icon: <Image className="size-5" /> },
  "calendar-center": { title: "Calendar Center", description: "Schedule campaigns, promotions, and retailer events in a unified calendar view.", icon: <Calendar className="size-5" /> },
  "media-plan": { title: "Media Plan", description: "Plan and coordinate media buys across retailers and channels.", icon: <Map className="size-5" /> },
  "cross-retailer-ads": { title: "Cross Retailer Ads", description: "Unified view of ad performance metrics spanning all retail media networks.", icon: <BarChart2 className="size-5" /> },
  "sov-dashboard": { title: "SOV Dashboard", description: "Monitor share of voice position for your brands on digital shelves.", icon: <LayoutGrid className="size-5" /> },
  "amz-multichannel": { title: "AMZ Multi-channel", description: "Track Amazon performance across all fulfilled and marketplace channels.", icon: <Package className="size-5" /> },
};

const ROLES: RoleDef[] = [
  {
    id: "executive",
    label: "Executive and business leader",
    categories: [
      {
        name: "Dashboard & KPIs",
        description: "Centralized views of business health, ROI metrics, and custom performance indicators",
        color: "#28c76f",
        items: [
          { id: "executive-dashboard", label: "Executive Dashboard", tooltip: "Cross-retailer overview of advertising performance, sales, ROAS, and automation impact." },
          { id: "custom-dashboard", label: "Custom Dashboard", tooltip: "Build personalized dashboards to track the metrics that matter most to your team." },
          { id: "custom-metric", label: "Custom Metric", tooltip: "Define bespoke KPIs and track them alongside standard Pacvue metrics." },
        ],
      },
      {
        name: "Performance Tracking",
        description: "Monitor account trends, competitive positioning, and operational efficiency gains",
        color: "#7367f0",
        items: [
          { id: "account-activity", label: "Account Activity Analysis", tooltip: "Deep-dive into account-level activity to understand performance trends." },
          { id: "cross-retailer-sov", label: "Cross Retailer SOV", tooltip: "Benchmark your share of voice across Amazon, Walmart, Target, and more." },
          { id: "automation-value", label: "Automation Value Insights", tooltip: "See the time saved and revenue generated by Pacvue's automation engines." },
        ],
      },
      {
        name: "Reports",
        description: "Tools & optimization for planning and execution",
        color: "#66a8ff",
        items: [
          { id: "incrementality", label: "Incrementality", tooltip: "Prove the true incremental sales lift driven by your ad spend." },
          { id: "budget-plan", label: "Budget Plan", tooltip: "Strategic budget allocation across brands, retailers, and fiscal periods." },
          { id: "keyword-opportunity", label: "Keyword Opportunity", tooltip: "Surface high-value keyword gaps before competitors find them." },
          { id: "share-tag", label: "Share Tag", tooltip: "Tag campaign insights and share with stakeholders in one click." },
          { id: "creative-hub", label: "Creative Hub", tooltip: "Organize, preview, and deploy creative assets across all campaigns." },
          { id: "calendar-center", label: "Calendar Center", tooltip: "Sync promotional calendars with ad scheduling to maximize event ROI." },
          { id: "media-plan", label: "Media Plan", tooltip: "Plan media investment across channels with integrated forecasting." },
        ],
      },
    ],
  },
  {
    id: "retail-media",
    label: "Retail media and ads manager",
    categories: [
      {
        name: "Campaign Planning",
        description: "Budget allocation, media planning, and campaign scheduling across retailers",
        color: "#28c76f",
        items: [
          { id: "budget-plan", label: "Budget Plan", tooltip: "Set pacing rules and allocate budget across campaigns in real time." },
          { id: "media-plan", label: "Media Plan", tooltip: "Coordinate media buys across retailer ad networks with one workflow." },
          { id: "calendar-center", label: "Calendar Center", tooltip: "Align campaigns with retail events, holidays, and tentpole moments." },
        ],
      },
      {
        name: "Optimization",
        description: "Find high-impact keyword opportunities, measure incrementality, and optimize bid strategy",
        color: "#7367f0",
        items: [
          { id: "keyword-opportunity", label: "Keyword Opportunity", tooltip: "Identify untapped keywords to expand reach and reduce wasted spend." },
          { id: "incrementality", label: "Incrementality", tooltip: "Measure which spend is truly driving new sales vs. capturing existing demand." },
          { id: "share-tag", label: "Share Tag", tooltip: "Segment audiences and share campaign tags across your team." },
        ],
      },
      {
        name: "Creative Assets",
        description: "Centralized hub for managing, organizing, and deploying creative content across campaigns",
        color: "#66a8ff",
        items: [
          { id: "creative-hub", label: "Creative Hub", tooltip: "Upload, review, and push creative assets directly to live campaigns." },
        ],
      },
      {
        name: "Performance",
        description: "Campaign metrics, cross-retailer ad performance, and custom analytics dashboards",
        color: "#0253b6",
        items: [
          { id: "cross-retailer-ads", label: "Cross Retailer Ads", tooltip: "Unified ROAS, CPC, and impression data across all retail ad platforms." },
          { id: "custom-dashboard", label: "Custom Dashboard", tooltip: "Drag-and-drop your most-used performance widgets into a single view." },
        ],
      },
    ],
  },
  {
    id: "ecommerce",
    label: "eCommerce and marketplace manager",
    categories: [
      {
        name: "Strategy — Executive Hub",
        description: "Strategic oversight for global performance, Segment health, and operational efficiency",
        color: "#28c76f",
        items: [
          { id: "executive-dashboard", label: "Executive Dashboard", tooltip: "High-level cross-retailer performance summary for leadership reporting." },
          { id: "automation-value", label: "Automation Value Insights", tooltip: "Quantify platform ROI and operational efficiency gains." },
          { id: "account-activity", label: "Account Activity Analysis", tooltip: "Track which account changes are driving or hurting marketplace performance." },
        ],
      },
      {
        name: "Analysis — Performance Analytics",
        description: "Reports & insights for cross-retailer performance analysis",
        color: "#7367f0",
        items: [
          { id: "cross-retailer-ads", label: "Cross Retailer Ads", tooltip: "Compare ad performance parity and gaps across Amazon, Walmart, and Target." },
          { id: "custom-dashboard", label: "Custom Dashboard", tooltip: "Build marketplace-specific dashboards for your category and brand." },
          { id: "sov-dashboard", label: "SOV Dashboard", tooltip: "Monitor digital shelf presence and organic ranking across retailers." },
          { id: "cross-retailer-sov", label: "Cross Retailer SOV", tooltip: "Benchmark share of voice vs. competitors across all retail platforms." },
          { id: "custom-metric", label: "Custom Metric", tooltip: "Track GMV, sell-through rate, and other eCommerce-specific KPIs." },
          { id: "amz-multichannel", label: "AMZ Multi-channel", tooltip: "Manage and report on all Amazon fulfillment and marketplace channels." },
        ],
      },
      {
        name: "Action — Campaign Management",
        description: "Tools & optimization for planning and execution",
        color: "#66a8ff",
        items: [
          { id: "incrementality", label: "Incrementality", tooltip: "Separate halo effects from true incremental revenue driven by ads." },
          { id: "budget-plan", label: "Budget Plan", tooltip: "Allocate seasonal budgets across categories and retail channels." },
          { id: "keyword-opportunity", label: "Keyword Opportunity", tooltip: "Discover search demand shifts to capitalize on emerging categories." },
          { id: "share-tag", label: "Share Tag", tooltip: "Tag promotions and share campaign segments with retail partners." },
          { id: "creative-hub", label: "Creative Hub", tooltip: "Manage product images, A+ content, and ad creatives in one place." },
          { id: "calendar-center", label: "Calendar Center", tooltip: "Coordinate promotional events with your retail partner's ad calendar." },
          { id: "media-plan", label: "Media Plan", tooltip: "Plan retail media investment aligned to category growth targets." },
        ],
      },
    ],
  },
  {
    id: "agency",
    label: "Agency and account manager",
    categories: [
      {
        name: "Client Management",
        description: "Overview of all client accounts, activity history, and customized client dashboards",
        color: "#ff6b6b",
        items: [
          { id: "account-activity", label: "Account Activity Analysis", tooltip: "Monitor activity across all client accounts in a single interface." },
          { id: "custom-dashboard", label: "Custom Dashboard", tooltip: "Build white-label dashboards for client-facing performance reviews." },
        ],
      },
      {
        name: "Campaign Operations",
        description: "Manage multi-client budgets, plan media buys, coordinate timelines, and track execution",
        color: "#ffa500",
        items: [
          { id: "budget-plan", label: "Budget Plan", tooltip: "Manage multi-client budgets with pacing alerts and reallocation tools." },
          { id: "media-plan", label: "Media Plan", tooltip: "Coordinate media buys across clients and retailers with one workflow." },
          { id: "calendar-center", label: "Calendar Center", tooltip: "Sync retailer promotional calendars across all client campaigns." },
        ],
      },
      {
        name: "Performance Reporting",
        description: "Client-ready performance reports, cross-retailer ad performance, and ROI dashboards",
        color: "#7367f0",
        items: [
          { id: "cross-retailer-ads", label: "Cross Retailer Ads", tooltip: "Generate client-ready performance reports across all retailer ad networks." },
          { id: "custom-dashboard", label: "Custom Dashboard", tooltip: "Pre-build report templates and share live links with clients." },
        ],
      },
      {
        name: "Execution",
        description: "Tools for rolling out campaigns across client accounts and retailer channels",
        color: "#28c76f",
        items: [
          { id: "share-tag", label: "Share Tag", tooltip: "Tag and share campaign segments across client accounts and teams." },
        ],
      },
    ],
  },
  {
    id: "analyst",
    label: "Analyst and insights team member",
    categories: [
      {
        name: "Cross-Retailer Analytics",
        description: "Analyze performance patterns, market trends, and competitive intelligence across all retailers",
        color: "#ffa500",
        items: [
          { id: "cross-retailer-ads", label: "Cross Retailer Ads", tooltip: "Analyze ad spend efficiency and ROAS trends across all retail partners." },
          { id: "cross-retailer-sov", label: "Cross Retailer SOV", tooltip: "Track competitive SOV shifts as a leading indicator of market share change." },
        ],
      },
      {
        name: "Custom Analysis",
        description: "Build flexible dashboards and custom metrics for deep-dive analysis",
        color: "#7367f0",
        items: [
          { id: "custom-dashboard", label: "Custom Dashboard", tooltip: "Compose analytical views from any metric combination in the platform." },
          { id: "custom-metric", label: "Custom Metric", tooltip: "Build proprietary metrics formulas for segment-specific analysis." },
        ],
      },
      {
        name: "Multi-Channel Insights",
        description: "Track performance across Amazon, Walmart, Target, Instacart, and other channels",
        color: "#00d4aa",
        items: [
          { id: "amz-multichannel", label: "AMZ Multi-channel", tooltip: "Analyze Amazon performance by channel: DSP, Sponsored, AMC, and more." },
          { id: "account-activity", label: "Account Activity Analysis", tooltip: "Identify performance anomalies and opportunity signals across all accounts." },
        ],
      },
      {
        name: "Deep Dives",
        description: "Access to all flexible tools for specialized analysis, custom reports, and ad-hoc queries",
        color: "#ff6b6b",
        items: [
          { id: "incrementality", label: "Incrementality", tooltip: "Run controlled incrementality tests to validate ad effectiveness hypotheses." },
          { id: "keyword-opportunity", label: "Keyword Opportunity", tooltip: "Explore keyword-level data to uncover long-tail and competitive opportunities." },
          { id: "sov-dashboard", label: "SOV Dashboard", tooltip: "Drill into shelf position data by category, keyword, and brand." },
        ],
      },
    ],
  },
  {
    id: "operations",
    label: "Operations and supply chain team member",
    categories: [
      {
        name: "Buy Box & Shelf",
        description: "Monitor Buy Box ownership, shelf position, and share of voice across retailers",
        color: "#00d4aa",
        items: [
          { id: "sov-dashboard", label: "SOV Dashboard", tooltip: "Track Buy Box win rates and organic shelf placement in real time." },
          { id: "cross-retailer-sov", label: "Cross Retailer SOV", tooltip: "Monitor your shelf position vs. competitors across all key retailers." },
        ],
      },
      {
        name: "Availability Monitoring",
        description: "Track inventory levels, out-of-stock incidents, fulfillment performance, and channel health",
        color: "#7367f0",
        items: [
          { id: "account-activity", label: "Account Activity Analysis", tooltip: "Detect stock-out events and fulfillment issues from activity signals." },
          { id: "amz-multichannel", label: "AMZ Multi-channel", tooltip: "Monitor availability across Amazon FBA, FBM, and marketplace sellers." },
        ],
      },
      {
        name: "Ops Dashboard",
        description: "Customizable operational dashboards for real-time inventory and logistics tracking",
        color: "#ffa500",
        items: [
          { id: "custom-dashboard", label: "Custom Dashboard", tooltip: "Build ops-specific dashboards with inventory, OOS, and logistics KPIs." },
          { id: "custom-metric", label: "Custom Metric", tooltip: "Define fill rates, OTIF scores, and other supply chain metrics." },
        ],
      },
      {
        name: "Revenue Recovery",
        description: "Identify and monitor lost sales opportunities, pricing issues, and availability-driven losses",
        color: "#ff6b6b",
        items: [
          { id: "incrementality", label: "Incrementality", tooltip: "Identify revenue lost to OOS events and quantify recovery opportunity." },
          { id: "budget-plan", label: "Budget Plan", tooltip: "Reallocate ad spend toward in-stock SKUs to minimize revenue leakage." },
        ],
      },
    ],
  },
];

// Full navigation: all unique items organized into broad categories
// All unique menu items sorted A–Z, used for the full navigation view
const ALL_ITEMS_SORTED: MenuItem[] = Object.entries(ALL_PAGES)
  .map(([id, page]) => ({
    id,
    label: page.title,
    tooltip: page.description,
  }))
  .sort((a, b) => a.label.localeCompare(b.label));

// ─── Tooltip Component ────────────────────────────────────────────────────────

const TIP_WIDTH = 256; // w-64
const TIP_GAP = 10;    // gap between item edge and tooltip box

function Tooltip({ text, children }: { text: string; children: React.ReactNode }) {
  const [pos, setPos] = useState<{ x: number; y: number; side: "right" | "left" } | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const show = () => {
    if (!containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    const wouldOverflow = rect.right + TIP_GAP + TIP_WIDTH > window.innerWidth - 8;
    const side = wouldOverflow ? "left" : "right";
    setPos({
      x: side === "right" ? rect.right + TIP_GAP : rect.left - TIP_GAP - TIP_WIDTH,
      y: rect.top + rect.height / 2,
      side,
    });
  };

  return (
    <div
      ref={containerRef}
      onMouseEnter={show}
      onMouseLeave={() => setPos(null)}
    >
      {children}
      {pos && createPortal(
        <div
          className="fixed z-[9999] pointer-events-none"
          style={{ left: pos.x, top: pos.y, width: TIP_WIDTH, transform: "translateY(-50%)" }}
        >
          {/* Arrow */}
          <div
            className={`absolute top-1/2 -translate-y-1/2 size-0 border-y-[6px] border-y-transparent ${
              pos.side === "right"
                ? "-left-[7px] border-r-[8px] border-r-[#323232]"
                : "-right-[7px] border-l-[8px] border-l-[#323232]"
            }`}
          />
          <div className="bg-[#323232] text-white text-xs leading-relaxed rounded-lg px-3 py-2.5 shadow-xl">
            {text}
          </div>
        </div>,
        document.body
      )}
    </div>
  );
}

// ─── Pacvue HQ Icon ───────────────────────────────────────────────────────────

function PacvueHQButton({ onClick, isOpen }: { onClick: () => void; isOpen: boolean }) {
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-1.5 pl-[5px] pr-4 py-[3px] rounded-[13px] border border-[#ff9f43] drop-shadow-[0px_4px_12px_rgba(0,0,0,0.06)] transition-all duration-150 hover:bg-[#fffaf5] hover:border-[#e8882e] hover:shadow-[0px_4px_16px_rgba(255,159,67,0.25)] active:scale-[0.97] ${isOpen ? "bg-[#fffaf5] border-[#e8882e] shadow-[0px_4px_16px_rgba(255,159,67,0.25)]" : "bg-[#f9fafb]"}`}
    >
      <div className="size-5 flex items-center justify-center">
        <svg viewBox="0 0 18 18" fill="none" className="size-[18px]">
          <rect width="18" height="18" rx="4" fill="#EDE9FE" />
          <path d="M9 3.5C6.51 3.5 4.5 5.51 4.5 8C4.5 9.38 5.13 10.61 6.12 11.44L5.5 14.5L8.24 13.05C8.49 13.09 8.74 13.12 9 13.12C11.49 13.12 13.5 11.11 13.5 8.62C13.5 6.13 11.49 3.5 9 3.5Z" fill="#7367F0" />
          <path d="M7.5 7.5L9 6L10.5 7.5L9 9L7.5 7.5Z" fill="white" opacity="0.7" />
        </svg>
      </div>
      <span className="font-semibold text-[13px] leading-[22px] text-[#82858b]">Pacvue HQ</span>
    </button>
  );
}

// ─── Role Dropdown ────────────────────────────────────────────────────────────

function RoleDropdown({
  selectedRole,
  onSelect,
  onClose,
}: {
  selectedRole: RoleId;
  onSelect: (r: RoleId) => void;
  onClose: () => void;
}) {
  return (
    <div className="absolute top-full left-0 mt-1 z-50 bg-white rounded-md shadow-[0px_4px_7px_rgba(0,0,0,0.12)] py-1.5 min-w-[280px] border border-gray-100">
      {ROLES.map((r) => (
        <button
          key={r.id}
          onClick={() => { onSelect(r.id); onClose(); }}
          className={`w-full text-left px-5 py-2.5 text-sm leading-5 font-normal transition-colors hover:bg-[#f5f5ff] ${selectedRole === r.id ? "text-[#7367f0] bg-[#f5f5ff] font-medium" : "text-[#12143c]"}`}
        >
          {r.label}
        </button>
      ))}
    </div>
  );
}

// ─── Nav Menu Panel ───────────────────────────────────────────────────────────

function NavMenuPanel({
  role,
  onNavigate,
  onClose,
}: {
  role: RoleDef | null;
  onNavigate: (page: PageId) => void;
  onClose: () => void;
}) {
  const categories = role ? role.categories : FULL_NAV_CATEGORIES;

  return (
    <div className="flex items-start overflow-x-auto">
      {categories.map((cat, i) => (
        <div
          key={i}
          className="flex-shrink-0 w-[300px] self-stretch border-r border-[#e5e7eb] last:border-r-0"
        >
          <div className="p-6 flex flex-col gap-5 h-full">
            {/* Category header */}
            <div className="flex flex-col gap-0.5 pb-[22px] border-b border-[#dedfe3]">
              <p
                className="text-sm font-semibold leading-6 uppercase tracking-wide"
                style={{ color: cat.color }}
              >
                {cat.name}
              </p>
              <p className="text-[13px] leading-5 text-[#82858b]">{cat.description}</p>
            </div>
            {/* Items */}
            <div className="flex flex-col gap-3">
              {cat.items.map((item) => (
                <Tooltip key={item.id} text={item.tooltip}>
                  <button
                    onClick={() => { onNavigate(item.id); onClose(); }}
                    className="text-left text-[15px] leading-6 text-[#4a5565] hover:text-[#7367f0] hover:translate-x-0.5 transition-all duration-150 w-full"
                  >
                    {item.label}
                  </button>
                </Tooltip>
              ))}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── Main Navigation Dropdown ─────────────────────────────────────────────────

function PacvueHQDropdown({
  selectedRole,
  onRoleChange,
  onNavigate,
  onClose,
}: {
  selectedRole: RoleId;
  onRoleChange: (r: RoleId) => void;
  onNavigate: (page: PageId) => void;
  onClose: () => void;
}) {
  const [roleDropdownOpen, setRoleDropdownOpen] = useState(false);
  const [showFullNav, setShowFullNavState] = useState(() => {
    const saved = localStorage.getItem("pacvue-nav-view");
    return saved ? JSON.parse(saved) : false;
  });
  const [search, setSearch] = useState("");
  const roleRef = useRef<HTMLDivElement>(null);

  const setShowFullNav = (value: boolean | ((prev: boolean) => boolean)) => {
    setShowFullNavState((prev) => {
      const newValue = typeof value === "function" ? value(prev) : value;
      localStorage.setItem("pacvue-nav-view", JSON.stringify(newValue));
      return newValue;
    });
  };

  const currentRole = ROLES.find((r) => r.id === selectedRole)!;

  // Close role dropdown on outside click
  useEffect(() => {
    function handler(e: MouseEvent) {
      if (roleRef.current && !roleRef.current.contains(e.target as Node)) {
        setRoleDropdownOpen(false);
      }
    }
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  // Role-view: filter categories by search
  const filteredCategories = (() => {
    if (!search.trim()) return currentRole.categories;
    const q = search.toLowerCase();
    return currentRole.categories
      .map((cat) => ({
        ...cat,
        items: cat.items.filter(
          (item) => item.label.toLowerCase().includes(q) || item.tooltip.toLowerCase().includes(q)
        ),
      }))
      .filter((cat) => cat.items.length > 0);
  })();

  // Full-nav: filter flat sorted list by search, then group by first letter
  const filteredAllItems = ALL_ITEMS_SORTED.filter((item) => {
    if (!search.trim()) return true;
    const q = search.toLowerCase();
    return item.label.toLowerCase().includes(q) || item.tooltip.toLowerCase().includes(q);
  });

  // Group items by first letter
  const itemsByLetter: Record<string, MenuItem[]> = {};
  filteredAllItems.forEach((item) => {
    const letter = item.label.charAt(0).toUpperCase();
    if (!itemsByLetter[letter]) itemsByLetter[letter] = [];
    itemsByLetter[letter].push(item);
  });
  const sortedLetters = Object.keys(itemsByLetter).sort();

  return (
    <div className="bg-white rounded-[10px] shadow-[0px_10px_15px_-3px_rgba(0,0,0,0.1),0px_4px_6px_-4px_rgba(0,0,0,0.1)] overflow-hidden flex flex-col">
      {/* Top bar: role selector + search */}
      <div className="border-b border-[#dedfe3] px-6 py-5 flex items-start justify-between gap-4 flex-wrap">
        {!showFullNav && (
          <div ref={roleRef} className="relative">
            <button
              onClick={() => setRoleDropdownOpen((v) => !v)}
              className="flex items-center gap-2.5 h-9 px-3 bg-white border border-[#dedfe3] rounded-[4px] text-sm"
            >
              <span className="font-medium text-[#45464f] whitespace-nowrap">View by role</span>
              <div className="h-4 w-px bg-[#dedfe3]" />
              <span className="font-normal text-[#66666c] whitespace-nowrap max-w-[180px] truncate">
                {currentRole.label}
              </span>
              <svg viewBox="0 0 10 7" fill="none" className="size-4 flex-shrink-0">
                <path clipRule="evenodd" d="M0.5 0.75L5 5.25L9.5 0.75" fill="none" stroke="#B2B2B8" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fillRule="evenodd" />
              </svg>
            </button>
            {roleDropdownOpen && (
              <RoleDropdown
                selectedRole={selectedRole}
                onSelect={(r) => { onRoleChange(r); setShowFullNav(false); }}
                onClose={() => setRoleDropdownOpen(false)}
              />
            )}
          </div>
        )}

        {/* Search */}
        <div className={`h-9 relative rounded-[4px] border border-[#dedfe3] bg-white flex items-center px-3 gap-2 ${showFullNav ? 'w-full' : 'flex-1 min-w-[180px] max-w-[289px]'}`}>
          <input
            className="flex-1 text-sm text-[#66666c] placeholder-[#66666c] outline-none bg-transparent"
            placeholder="Search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <Search className="size-4 text-[#66666c] flex-shrink-0" />
        </div>
      </div>

      {/* Menu columns */}
      <div>
        {showFullNav ? (
          /* ── Full navigation: alphabetical index ── */
          filteredAllItems.length > 0 ? (
            <div className="px-6 py-5 flex flex-col gap-4 max-h-96 overflow-y-auto">
              {sortedLetters.map((letter) => (
                <div key={letter}>
                  <p className="text-xs font-semibold text-[#82858b] uppercase tracking-wide mb-2">{letter}</p>
                  <div className="flex flex-col gap-2">
                    {itemsByLetter[letter].map((item) => (
                      <Tooltip key={item.id} text={item.tooltip}>
                        <button
                          onClick={() => { onNavigate(item.id); onClose(); }}
                          className="text-left text-sm leading-6 text-[#4a5565] hover:text-[#7367f0] hover:translate-x-0.5 transition-all duration-150 w-full"
                        >
                          {item.label}
                        </button>
                      </Tooltip>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="p-8 text-center text-sm text-[#82858b]">No results for &ldquo;{search}&rdquo;</div>
          )
        ) : (
          /* ── Role-specific: categorised columns ── */
          filteredCategories.length > 0 ? (
            <div className="flex items-start">
              {filteredCategories.map((cat, i) => (
                <div key={i} className="flex-shrink-0 w-[300px] self-stretch border-r border-[#e5e7eb] last:border-r-0">
                  <div className="p-6 flex flex-col gap-5 h-full">
                    <div className="flex flex-col gap-0.5 pb-[22px] border-b border-[#dedfe3]" style={{ minHeight: 88 }}>
                      <p className="text-base font-semibold leading-6 uppercase" style={{ color: cat.color }}>
                        {cat.name}
                      </p>
                      <p className="text-sm leading-5 text-[#82858b]">{cat.description}</p>
                    </div>
                    <div className="flex flex-col gap-3">
                      {cat.items.map((item) => (
                        <Tooltip key={item.id} text={item.tooltip}>
                          <button
                            onClick={() => { onNavigate(item.id); onClose(); }}
                            className="text-left text-base leading-6 text-[#4a5565] hover:bg-[#fff4ec] transition-colors duration-100 w-full rounded-sm px-2 -mx-2"
                          >
                            {item.label}
                          </button>
                        </Tooltip>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="p-8 text-center text-sm text-[#82858b]">No results for &ldquo;{search}&rdquo;</div>
          )
        )}
      </div>

      {/* Footer: toggle full nav */}
      <div className="border-t border-[#dedfe3] px-6 py-5 flex justify-center">
        <button
          onClick={() => setShowFullNav((v) => !v)}
          className="flex items-center gap-2 py-2 text-sm font-medium text-[#ff9f43] hover:text-[#e8882e] transition-colors"
        >
          <svg viewBox="0 0 20 20" fill="none" className="size-5">
            <path d="M3 5H17M3 10H17M3 15H11" stroke="#FF9F43" strokeWidth="1.5" strokeLinecap="round" />
          </svg>
          {showFullNav ? "View role-specific menu" : "View full navigation menu"}
        </button>
      </div>
    </div>
  );
}

// ─── Page Content Overlay ─────────────────────────────────────────────────────

function PageOverlay({ pageId, onClose }: { pageId: PageId; onClose: () => void }) {
  const page = ALL_PAGES[pageId];
  if (!page) return null;

  return (
    <div
      className="absolute inset-0 z-20 flex items-center justify-center"
      style={{ background: "rgba(249,250,251,0.92)", backdropFilter: "blur(2px)" }}
    >
      <div className="flex flex-col items-center gap-6 max-w-2xl w-full px-8">
        {/* Close */}
        <button
          onClick={onClose}
          className="absolute top-8 right-8 size-9 flex items-center justify-center rounded-full bg-white border border-[#e5e7eb] text-[#667085] hover:bg-gray-50 shadow-sm"
        >
          <svg viewBox="0 0 16 16" fill="none" className="size-4">
            <path d="M12 4L4 12M4 4l8 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
          </svg>
        </button>

        <div className="flex flex-col items-center gap-3 text-center">
          <div className="size-14 rounded-2xl bg-[#ede9fe] flex items-center justify-center text-[#7367f0]">
            {page.icon}
          </div>
          <h1 className="text-2xl font-semibold text-[#101828]">{page.title}</h1>
          <p className="text-sm text-[#82858b] leading-6 max-w-sm">{page.description}</p>
        </div>

        {/* Chart */}
        <div className="w-full rounded-xl border border-[#e5e7eb] bg-white overflow-hidden shadow-sm">
          <div className="px-5 py-3.5 border-b border-[#e5e7eb] flex items-center justify-between">
            <p className="text-sm font-semibold text-[#101828]">Performance Overview</p>
            <div className="flex items-center gap-1.5">
              {["7D", "30D", "90D"].map((d) => (
                <button key={d} className={`px-2 py-0.5 text-xs rounded font-medium ${d === "30D" ? "bg-[#ede9fe] text-[#7367f0]" : "text-[#82858b] hover:bg-gray-50"}`}>
                  {d}
                </button>
              ))}
            </div>
          </div>
          <div className="px-5 py-4">
            <div className="h-36 flex items-end gap-1.5">
              {[40, 65, 45, 80, 60, 90, 70, 85, 55, 75, 95, 65].map((h, i) => (
                <div key={i} className="flex-1 flex flex-col justify-end">
                  <div className="rounded-t bg-gradient-to-t from-[#7367f0] to-[#a89df9] opacity-80 hover:opacity-100 transition-opacity" style={{ height: `${h}%` }} />
                </div>
              ))}
            </div>
            <div className="flex justify-between mt-1.5">
              {["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"].map((m) => (
                <span key={m} className="text-[10px] text-[#82858b]">{m}</span>
              ))}
            </div>
          </div>
        </div>

        {/* KPIs */}
        <div className="grid grid-cols-4 gap-3 w-full">
          {[
            { label: "Total Spend", value: "$2.4M", delta: "+12%", up: true },
            { label: "ROAS", value: "4.2x", delta: "+0.3x", up: true },
            { label: "Impressions", value: "48.7M", delta: "-2%", up: false },
            { label: "Conversions", value: "18,432", delta: "+8%", up: true },
          ].map((kpi) => (
            <div key={kpi.label} className="bg-white rounded-xl border border-[#e5e7eb] px-4 py-3 shadow-sm">
              <p className="text-xs text-[#82858b] mb-1">{kpi.label}</p>
              <p className="text-lg font-semibold text-[#101828]">{kpi.value}</p>
              <p className={`text-xs font-medium mt-0.5 ${kpi.up ? "text-[#28c76f]" : "text-[#ea5455]"}`}>{kpi.delta}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── App Shell ────────────────────────────────────────────────────────────────

export default function App() {
  const [navOpen, setNavOpen] = useState(false);
  const [selectedRole, setSelectedRole] = useState<RoleId>("executive");
  const [currentPage, setCurrentPage] = useState<PageId | null>(null);
  const navRef = useRef<HTMLDivElement>(null);

  // Close nav on outside click
  useEffect(() => {
    function handler(e: MouseEvent) {
      if (navRef.current && !navRef.current.contains(e.target as Node)) {
        setNavOpen(false);
      }
    }
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  return (
    <div
      data-canvas
      className="relative overflow-hidden"
      style={{ width: 1440, height: 810 }}
    >
        {/* Background image */}
        <img
          src={bgImage}
          alt=""
          className="absolute inset-0 w-full h-full object-cover object-top pointer-events-none select-none"
        />

        {/* Pacvue HQ trigger button — matches Figma: left-[206px] top-[17px] */}
        <div ref={navRef} className="absolute" style={{ left: 206, top: 17 }}>
          <PacvueHQButton onClick={() => setNavOpen((v) => !v)} isOpen={navOpen} />

          {/* Dropdown panel — appears at top-[47px] per Figma (30px below button top) */}
          {navOpen && (
            <div className="absolute left-0 z-50" style={{ top: 30 }}>
              <PacvueHQDropdown
                selectedRole={selectedRole}
                onRoleChange={(r) => setSelectedRole(r)}
                onNavigate={(p) => setCurrentPage(p)}
                onClose={() => setNavOpen(false)}
              />
            </div>
          )}
        </div>

        {/* Page content overlay */}
        {currentPage && (
          <PageOverlay pageId={currentPage} onClose={() => setCurrentPage(null)} />
        )}
    </div>
  );
}
